# Generated by Django 4.2.1 on 2023-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='recommend_video',
            name='user_recommend',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
